import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy | Clinic Launch Academy',
  description:
    'Learn how Clinic Launch Academy collects, uses, discloses, and safeguards personal information for its programs and services.',
}

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[#0c0a05] text-white py-24">
      <div className="max-w-5xl mx-auto px-4 md:px-8 space-y-12">
        <header className="space-y-4">
          <p className="text-sm uppercase tracking-wide text-white/50">Privacy Policy</p>
          <h1 className="text-3xl md:text-5xl font-semibold">Privacy Policy for Clinic Launch Academy</h1>
          <p className="text-white/70">Last updated: October 31, 2025</p>
          <p className="text-white/80 leading-relaxed">
            This Privacy Policy describes how Clinic Launch Academy (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or
            &ldquo;our&rdquo;) collects, uses, discloses, and safeguards personal information when you
            interact with our websites, digital properties, and services (collectively, the
            &ldquo;Service&rdquo;). By using the Service, you agree to the collection and use of your
            information in accordance with this Privacy Policy.
          </p>
        </header>

        <section className="space-y-6">
          <h2 className="text-2xl font-semibold">Interpretation and Definitions</h2>
          <div className="space-y-4 text-white/80 leading-relaxed">
            <p>
              Capitalized terms have the meanings described below. The definitions apply
              whether the terms appear in singular or plural form.
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>
                <strong>Account</strong> means a unique profile created for you to access our
                Service or portions of the Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is controlled by, or is
                under common control with a party, where &ldquo;control&rdquo; means ownership of 50% or
                more of the shares, equity interest, or other securities entitled to vote for
                the election of directors or other managing authority.
              </li>
              <li>
                <strong>Company</strong> (referred to as &ldquo;Clinic Launch Academy&rdquo;, &ldquo;the
                Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) refers to Clinic Launch Academy, a program
                operated by Built By Design Businesses LLC, 5900 Balcones Drive, Suite 100,
                Austin, TX 78731.
              </li>
              <li>
                <strong>Cookies</strong> are small files placed on your computer, mobile device,
                or other device by a website. Cookies store information related to your browsing
                history and are used for authentication, personalization, and analytics.
              </li>
              <li>
                <strong>Country</strong> refers to Texas, United States.
              </li>
              <li>
                <strong>Device</strong> means any device that can access the Service, such as a
                computer, mobile phone, or tablet.
              </li>
              <li>
                <strong>Personal Data</strong> means any information that relates to an identified
                or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Clinic Launch Academy websites, programs,
                digital content, and related offerings.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal person who processes
                data on behalf of the Company. This includes third-party companies or
                individuals engaged to facilitate the Service, provide it on our behalf, assist
                us in analyzing usage, or deliver related services.
              </li>
              <li>
                <strong>Third-party Social Media Service</strong> means any website or social
                network that allows a user to log in or create an account to access the Service.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected automatically, generated by
                the use of the Service, or from the Service infrastructure itself (for example,
                analytics on time spent on a page).
              </li>
              <li>
                <strong>Website</strong> refers to Clinic Launch Academy, accessible at{' '}
                <Link href="https://cliniclaunchacademy.com" className="text-[#b38d38]">
                  https://cliniclaunchacademy.com
                </Link>
                .
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the Service, or the
                company or other legal entity on behalf of which such individual is accessing or
                using the Service, as applicable.
              </li>
            </ul>
          </div>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Collecting and Using Your Personal Data</h2>
          <h3 className="text-xl font-semibold">Types of Data Collected</h3>
          <p className="font-semibold text-white">Personal Data</p>
          <p>
            While using our Service, we may ask you to provide certain personally identifiable
            information that can be used to contact or identify you. Personally identifiable
            information may include:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>Email address</li>
            <li>First and last name</li>
            <li>Phone number</li>
            <li>Mailing address, including city, state, province, ZIP/Postal code</li>
            <li>Professional or business information related to your clinic operations</li>
          </ul>
          <p>
            You can opt out of receiving promotional SMS messages at any time by replying STOP
            or UNSUBSCRIBE. Transactional messages may still be sent where permitted by law.
          </p>
          <p className="font-semibold text-white">Usage Data</p>
          <p>
            Usage Data is collected automatically when you interact with the Service and may
            include your device&apos;s Internet Protocol (IP) address, browser type, browser
            version, the pages you visit, the time and date of your visit, time spent on those
            pages, unique device identifiers, and other diagnostic data. When you access the
            Service on a mobile device, we may collect additional information such as device
            type, unique identifiers, mobile operating system, and mobile browser type.
          </p>
          <h3 className="text-xl font-semibold">Information from Third-Party Social Media Services</h3>
          <p>
            If you choose to register or log in through a third-party social media service such
            as Google, Facebook, Instagram, Twitter, or LinkedIn, we may collect personal data
            associated with that account, including your name, email address, activities, and
            contacts. By linking these accounts, you authorize us to collect and store this
            information in accordance with this Privacy Policy.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Tracking Technologies and Cookies</h2>
          <p>
            We use cookies, pixels, and similar tracking technologies to monitor activity on the
            Service and store certain information. Cookies can be session-based (removed when you
            close your browser) or persistent (remain on your device until deleted). You may
            instruct your browser to refuse cookies; however, some features may not function
            without them.
          </p>
          <p className="font-semibold text-white">We use the following types of cookies:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong>Necessary / Essential Cookies</strong> (Session, administered by us) for
              authentication and security.
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong> (Persistent,
              administered by us) to remember your cookie preferences.
            </li>
            <li>
              <strong>Functionality Cookies</strong> (Persistent, administered by us) to retain
              your settings and preferences, such as login information or language.
            </li>
          </ul>
          <p>
            For more information about the cookies we use and your choices, please refer to this
            Privacy Policy&apos;s Cookies section or our dedicated Cookies Policy, if available.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>To provide, maintain, and improve the Service.</li>
            <li>To manage your Account and enable access to Service functionality.</li>
            <li>
              To fulfill a contract, including enrollment in Clinic Launch Academy programs and
              related transactions.
            </li>
            <li>
              To contact you by email, phone, SMS, or similar communications regarding updates,
              program details, and security notices.
            </li>
            <li>
              To provide news, offers, and information about services similar to those you have
              already purchased or inquired about, unless you opt out.
            </li>
            <li>To respond to and manage your inquiries, requests, and support tickets.</li>
            <li>
              To evaluate or conduct business transactions such as mergers, acquisitions, or
              financing where personal data may be part of the transferred assets.
            </li>
            <li>To perform data analysis, usage trend identification, and marketing optimization.</li>
            <li>To protect our legal rights and enforce our agreements.</li>
          </ul>
          <p>
            We may share your personal information with Service Providers, affiliates, business
            partners, or other users where applicable, and only in accordance with this Privacy
            Policy or with your consent.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Retention of Your Personal Data</h2>
          <p>
            We retain Personal Data only as long as necessary for the purposes described in this
            Privacy Policy. We retain Usage Data for shorter periods unless it is required to
            enhance security, improve functionality, or comply with legal obligations. When we no
            longer need personal information, we take reasonable steps to delete, anonymize, or
            securely store it.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Transfer of Your Personal Data</h2>
          <p>
            Your information may be processed at our operating offices and in other locations
            where parties involved in the processing are situated. This means your information may
            be transferred to and maintained on systems located outside your state, province, or
            country. By using the Service, you consent to such transfers.
          </p>
          <p>
            We take reasonable measures to ensure your data is handled securely and in accordance
            with this Privacy Policy, and we only transfer personal data to organizations or
            countries with adequate safeguards in place.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Delete Your Personal Data</h2>
          <p>
            You have the right to request deletion of the personal data we hold about you. You may
            manage or remove certain information within your account settings where available. You
            may also contact us to request access to, correct, or delete personal data that you
            have provided. We may retain certain information as required by law or for legitimate
            business purposes, such as recordkeeping or dispute resolution.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Disclosure of Your Personal Data</h2>
          <p className="font-semibold text-white">Business Transactions</p>
          <p>
            If we are involved in a merger, acquisition, or asset sale, your personal data may be
            transferred. We will provide notice before your personal data becomes subject to a
            different privacy policy.
          </p>
          <p className="font-semibold text-white">Law Enforcement</p>
          <p>
            Under certain circumstances, we may be required to disclose your personal data if
            required by law or in response to valid requests by public authorities.
          </p>
          <p className="font-semibold text-white">Other Legal Requirements</p>
          <p>We may disclose your information in good faith to:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend our rights or property</li>
            <li>Prevent or investigate possible wrongdoing related to the Service</li>
            <li>Protect the personal safety of users or the public</li>
            <li>Protect against legal liability</li>
          </ul>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Security of Your Personal Data</h2>
          <p>
            We implement commercially reasonable administrative, technical, and physical
            safeguards to protect your personal data. However, no method of transmission over the
            Internet or electronic storage is completely secure, and we cannot guarantee absolute
            security.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Children&apos;s Privacy</h2>
          <p>
            Our Service is not directed to individuals under the age of 13, and we do not
            knowingly collect personal data from children. If you become aware that a child has
            provided us with personal information without parental consent, please contact us so we
            can take appropriate action.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Links to Other Websites</h2>
          <p>
            Our Service may contain links to third-party websites or services that are not
            operated by us. We are not responsible for the content, privacy policies, or practices
            of these third-party sites. We encourage you to review the privacy policy of every site
            you visit.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Changes to This Privacy Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will post the revised version
            on this page and update the &ldquo;Last updated&rdquo; date. When material changes are made, we
            will provide additional notice as required by law. Continued use of the Service after
            changes become effective constitutes acceptance of the updated Privacy Policy.
          </p>
        </section>

        <section className="space-y-4 text-white/80 leading-relaxed">
          <h2 className="text-2xl font-semibold">Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy or our privacy practices, please
            contact us at{' '}
            <Link href="mailto:info@cliniclaunchacademy.com" className="text-[#b38d38]">
              info@cliniclaunchacademy.com
            </Link>
            .
          </p>
        </section>
      </div>
    </main>
  )
}
